lfucg/lexingtonky.gov

sites/default/settings.php
I have tested this locally by manually setting the env variable then checking the configs with drush. Let me know if you see any issues with it.
Thanks!
Matt
=> Disable the devel module on live. On all other envs enable it and change the mail interface

themes/custom/lex/js/join-police.js, themes/custom/lex/lex.libraries.yml, themes/custom/lex/lex.theme
Adds this script and iframe to the Join the Lexington Police "Landing Page". 
I conditionally attach the library I created to the page in a theme_preprocess_page hook in the .theme file.
=> LG-30 Adding script and iframe to /joinlexpolice

themes/custom/lex/templates/pages/page.html.twig
- removes div for iframe pages
=> Reverts empty div from page html twig

modules/custom/lex_custom/lex_custom.module
- adds update hook for drupal core issue
=> Taxonomy Moderation state fix

config/sync/core.menu.static_menu_link_overrides.yml, config/sync/taxonomy_menu.taxonomy_menu.lex_topic_navigation.yml, themes/custom/lex/js/browse-columns.js
- Handled undefined property conditions.
- Added desciptions to the taxonomy menu in drupal admin menu.
- Manually moved menu links to be in alphabetical order.
=> LG-67 Fix main menu navigation

config/sync/block.block.breadcrumbs.yml, config/sync/block.block.exposedformsolr_searchpage_1_2.yml, config/sync/block.block.fieldblock_body.yml, config/sync/block.block.fieldblock_field_organization_services.yml, config/sync/block.block.fieldblock_page_section.yml, config/sync/block.block.lex_headerquicklinks.yml, config/sync/block.block.lex_help.yml, config/sync/block.block.lex_home_edithomepagebanner.yml, config/sync/block.block.lex_home_messages.yml, config/sync/block.block.lex_home_mostactivepages.yml, config/sync/block.block.lex_home_views_block__front_page_news_block_1.yml, config/sync/block.block.lex_home_views_block__site_wide_notice_block.yml, config/sync/block.block.lex_home_views_block__taxonomy_top_level_block_1.yml, config/sync/block.block.lex_messages.yml, config/sync/block.block.mostpopularsearches.yml, config/sync/block.block.mostpopularsearches_2.yml, config/sync/block.block.views_block__front_page_news_block_2.yml, config/sync/block.block.views_block__front_page_news_block_org_page_news.yml, config/sync/block.block.views_block__sibling_pages_block_sidebar.yml, config/sync/block.block.views_block__sibling_pages_full_bleed.yml, config/sync/block.block.views_block__site_wide_notice_block.yml, config/sync/captcha.settings.yml, config/sync/field.field.contact_message.page_feedback.field_page_suggestion.yml, config/sync/honeypot.settings.yml, themes/custom/lex/js/scripts.js
LG-61 Fixes validation for front page feedback form
- comments out code in scripts.js, which sercumvented the capthca validation
- updated honeypot config
- moved status messages block to top of lex_home block layout
=> LG-61 Fixes validation for front page feedback form

composer.json, composer.lock
Credit: https://www.drupal.org/project/dropzonejs/issues/3198420#comment-14016903
=> Fixed missing library for dropzonejs

.circleci/config.yml, composer.lock
```
Gathering patches for root package.
> DrupalComposerManaged\ComposerScripts::preUpdate
Using version 'dev-main' for path repositories.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 7 updates, 0 removals
- Upgrading consolidation/annotated-command (4.7.0 => 4.7.1)
- Upgrading consolidation/robo (3.0.10 => 4.0.2)
- Upgrading drupal/core (9.4.8 => 9.4.9)
- Upgrading drupal/core-composer-scaffold (9.4.8 => 9.4.9)
- Upgrading drupal/core-recommended (9.4.8 => 9.4.9)
- Upgrading drupal/masquerade (dev-2.x a2dea44 => dev-2.x 8a9cb9d)
- Upgrading solarium/solarium (6.2.7 => 6.2.8)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 7 updates, 0 removals
- Syncing drupal/masquerade (dev-2.x …
```
=> Update Composer dependencies (2022-12-08-00-06)

web/themes/custom/lex/js/lex-cal.js, web/themes/custom/lex/scss/_calendar.scss
- fixed overlapping sidebar
- fixed problem with glitchy mobile mode
- adjusted font size and style to make mobile mode more usable
=> LG-49 Fix Calendar

config/sync/views.view.taxonomy_term.yml, web/modules/custom/lex_calendar/templates/calendar-page.html.twig
- the page_1 display Draggableviews wasn't leveraging the page_2 for sorting
=> LG-82 Fixes sorting of council members on the menu

.gitignore, composer.json, composer.lock, config/sync/captcha.settings.yml, config/sync/config_ignore.settings.yml, config/sync/core.extension.yml, config/sync/image_captcha.settings.yml
- ignores sensitive configuration
=> LG-80 Adds Recaptcha

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/eu_cookie_compliance.cookie_category.performance.yml, config/sync/eu_cookie_compliance.cookie_category.required.yml, config/sync/eu_cookie_compliance.cookie_category.statistics.yml, config/sync/eu_cookie_compliance.settings.yml, config/sync/user.role.anonymous.yml, web/themes/custom/lex/scss/main.scss, web/themes/custom/lex/scss/regions/_cookie_popup.scss
- adds EU module
- custom styling for module
- creates new content page for cookie compliance info
=> LG-107 Creates Cookie Compliance

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/extlink.settings.yml, web/themes/custom/lex/scss/atoms/_ext_link.scss, web/themes/custom/lex/scss/main.scss
Added new module for handling external link icons and styling for it.
You can find without too much difficulty external links on the site, but you can easily edit a news article, and test it by hyperlinking text to have the icon placed next to it.
| Documentation reflects changes? | No need
| Unit/Functional tests reflect changes? | No need
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-119
=> LG-119 Adds external link icons

composer.json, composer.lock, config/sync/core.extension.yml, web/themes/custom/lex/old_scss/_layout.sass, web/themes/custom/lex/old_scss/styles.sass, web/themes/custom/lex/scss/main.scss, web/themes/custom/lex/scss/molecules/_news_card.scss, web/themes/custom/lex/scss/pages/_article.scss, web/themes/custom/lex/templates/nodes/node--news-article.html.twig, web/themes/custom/lex/templates/pages/page.html.twig
Lots to sift through and clean up but for the most part just created some overrides using parent selectors. 
Separated the article stuff into it's own file, even if it's a little late to start doing that. 
Messed around with some breakpoints stuff and cleaned up the node page template.
Use the Multidev to visit pages for all the content types. 
- News Articles
- Organization Pages
- Board/Commission
- Service Guides
No need now with Multidev.
| Did you perform a self-review of this PR? | yes
| Did you perform browser testing? | yes, FF and Chrome
| Did you provide detail in the summary on how and where to test this branch? | yep
| Relevant links | JIRA issue, …
=> Max width updates, drop news sidebar down

config/sync/extlink.settings.yml
Removes external link icon from addtoany block
Look at addtoany block on /code-of-ordinances-and-zoning-ordinance
| Did you perform a self-review of this PR? | YES
| Documentation reflects changes? | N/A
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-123
=> LG-123 Removes extlink from addtoany

web/modules/custom/lex_custom/lex_custom.module
Re-adds missing events and meetings deletion hooks.
Go to the content page, filter by content type, and filter by updated ascending
| Did you perform browser testing? | n/a
| Did you provide detail in the summary on how and where to test this branch? | n/a
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-74
=> Adds meeting and event deletion to custom module

config/sync/core.extension.yml
Uninstalls editor_advanced_link
none
| Did you perform browser testing? | n/a
| Did you provide detail in the summary on how and where to test this branch? | n/a
| Relevant links | JIRA issue, bug reports, security alerts, etc.https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-130
=> LG-130 Uninstalls editor_advanced_link

config/sync/image.style.icon_button_image.yml, web/themes/custom/lex/patterns/molecules/icon-button-with-description.twig, web/themes/custom/lex/scss/molecules/_icon_button_with_description.scss
Removes images style for the paragraph to improve image quality of pngs, and adjusts styling for spacing of img and text
go to /public-input and check the buttons
| Unit/Functional tests reflect changes? |  n/a
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-133
=> LG-133 Adjusts spacing and image quality of icon desc button paragarph

web/themes/custom/lex/patterns/components/header.twig, web/themes/custom/lex/scss/regions/_header.scss
Shrinks the logo and header area
None required
| Did you provide detail in the summary on how and where to test this branch? | n/a
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-137
=> LG-137 Shrinks Logo and header height

web/themes/custom/lex/templates/includes/email.html.twig, web/themes/custom/lex/templates/pages/page.html.twig, web/themes/custom/lex_police/templates/page.html.twig
Swaps out "Email Us" with the actual email address
View contact blocks to see the change
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-134
=> LG-134 Prints out the email address in the contact block

web/themes/custom/lex/scss/molecules/_card_button.scss
n/a
n/a
| Unit/Functional tests reflect changes? |. n/a
| Did you perform browser testing? Yes
| Did you provide detail in the summary on how and where to test this branch? | n/a
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-140
=> LG-140 Swaps border for box-shadow to prevent content shifting on hover

config/sync/user.role.authenticated.yml
Auth user should be able to schedule publish 
Sign in as auth user to then schedule content publication
n/a
| Did you perform browser testing? | n/a
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-142
=> LG-142 Adds authenticated user role to schedule content publication

config/sync/core.entity_view_display.node.news_article.front_page_news.yml, config/sync/views.view.front_page_news.yml, web/themes/custom/lex/old_scss/_layout.sass, web/themes/custom/lex/old_scss/elements/_button.sass, web/themes/custom/lex/patterns/molecules/contact-card.twig, web/themes/custom/lex/patterns/molecules/news-card.twig, web/themes/custom/lex/scss/homepage/_blocks.scss, web/themes/custom/lex/scss/homepage/_hero__homepage.scss, web/themes/custom/lex/scss/main.scss, web/themes/custom/lex/scss/molecules/_event_card.scss, web/themes/custom/lex/scss/molecules/_news_card.scss, web/themes/custom/lex/templates/blocks/block--homeevents.html.twig, web/themes/custom/lex/templates/blocks/block--homemeetings.html.twig, web/themes/custom/lex/templates/blocks/block--urbancountycouncilhtml.html.twig, web/themes/custom/lex/templates/blocks/block--views-block--front-page-news-block-1.html.twig, web/themes/custom/lex/templates/nodes/node--news-article--front-page-news.html.twig, web/themes/custom/lex/templates/views/views-view-unformatted--front-page-news--block-1.html.twig, web/themes/custom/lex/templates/views/views-view-unformatted--front-page-news--block-2.html.twig
- Max width on content
- Event/Meetings cleanup and massaging
- more maintainable urbancountycouncil block
Just trying to do some housekeeping. Weird markup and weird CSS all over the place makes it a bit difficult.
Check out the homepage. I _**think**_ the changes only touched the homepage
| Did you perform a self-review of this PR? | yes
| Did you perform browser testing? | yes, Chrome, FF
| Did you provide detail in the summary on how and where to test this branch? | yes
| Relevant links | https://apaxsoftware.atlassian.net/browse/LG-138
=> TLC for homepage

web/themes/custom/lex/old_scss/_layout.sass
| Did you perform a self-review of this PR? |
| Documentation reflects changes? |
| Unit/Functional tests reflect changes? |
| Did you perform browser testing? |
| Did you provide detail in the summary on how and where to test this branch? |
| Relevant links | JIRA issue, bug reports, security alerts, etc.
=> Fixes padding on org, department pages

web/themes/custom/lex/scss/molecules/_news_card.scss, web/themes/custom/lex/templates/fields/field--node--body--news-article.html.twig, web/themes/custom/lex/templates/nodes/node--news-article--front-page-news.html.twig
Adjusts the front page news to use the summary.
Check out the homepage to make sure it matches. 
| Did you perform a self-review of this PR? | yes
| Did you perform browser testing? | no
| Did you provide detail in the summary on how and where to test this branch? | yes.
| Relevant links | Reported by Nick Brock.
=> update template for front page news to the summary

web/themes/custom/lex/js/lex-neighborhood-associations.js
Adds a if statement to check for already included results in associations array
Go go /find-your-neighborhood-association to test the search results
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?modal=detail&selectedIssue=LG-144
=> LG-144 Adds new check to eliminate duplicated results in js file

web/themes/custom/lex/js/lex-traffic-ticker.js, web/themes/custom/lex/lex.libraries.yml
| Did you perform a self-review of this PR? |
| Documentation reflects changes? |
| Unit/Functional tests reflect changes? |
| Did you perform browser testing? |
| Did you provide detail in the summary on how and where to test this branch? |
| Relevant links | JIRA issue, bug reports, security alerts, etc.
=> Fixing incidentType with Josh

config/sync/views.view.taxonomy_term.yml
Alters view to remove archived pages
Go to /browse/recreation/athletics and test archiving pages and make sure they are removed
| Relevant links | JIRA issue, bug reports, security alerts, etc.
=> Alters taxonomy_term view to remove archived pages from menu

web/themes/custom/lex/scss/_econdev.scss
Fixes scroll bars on windows machines
Go to https://lexky-d8.lndo.site/economic-development/lexwork on browserstack with a windows emulator 
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?selectedIssue=LG-157
=> LG-157 Fixes crazy scroll bars on Windows Machines on EconPage

web/modules/custom/addtocal/src/Controller/AddtocalController.php
Fixes add to calendar because of php implode deprecation
Add a event to your calendar
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?selectedIssue=LG-158
=> LG-158 Fixes Add to cal bug, php deprecation

web/themes/custom/lex/templates/html.html.twig
Adds new script
Inspect the page and see it in the <head>
| Relevant links | JIRA issue, bug reports, security alerts, etc. https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68?selectedIssue=LG-159
=> LG-159 Adding script Nick asked to place on site.

web/themes/custom/lex/lex.theme
Adds this code line to this page. 
Inspect the page and see it.
| Relevant links | JIRA issue, bug reports, security alerts, etc.
https://apaxsoftware.atlassian.net/jira/software/c/projects/LG/boards/68
=> LG-164 adds pixel to livegreen html head
